it:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_it
  pool: 10
  timeout: 5000
  port: 5432
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_development
  pool: 5
  username: time_dev
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_test
  pool: 5
  username: time_test
  password: password
  host: localhost
  port: 5432