it:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: time_it
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432
  
development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: time_development
  pool: 5
  username: postgres
  password:  password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: time_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

