it:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_it
  pool: 10
  username: postgres
  password: password
  timeout: 5000
  port: 5432
  host: db



development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_development
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_test
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432