it:
  adapter: postgresql
  encoding: unicode
  database: timesheet_it
  pool: 10
  username: timesheet_it
  password: 605587b0f9a1c4c91e6022adec873c87
  port: 5432
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_development
  pool: 5
  username: time_dev
  password: password
  host: 127.0.0.1
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: timesheet_test
  pool: 5
  username: time_test
  password: password
  host: localhost
  port: 5432